//
//  AvailableRoom.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.18
//

import Foundation
import UIKit
import AWSDynamoDB

class AvailableRoomFirBModel {
    
    var leaderId: String?
    var playerInRoom: [String:Any]?
    var roomType: String?
    var roomImageUrl: String?
    
    init(leaderId: String, playerInRoom: [String:Any], roomType: String, roomImageUrl: String){
        self.leaderId = leaderId
        self.playerInRoom = playerInRoom
        self.roomType = roomType
        self.roomImageUrl = roomImageUrl
    }
}
